# Generated by Django 4.2.5 on 2023-11-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_massage',
            new_name='contact_message',
        ),
    ]
